### PR TITLE
Set "aggregate" attribute for Dia version=2 associations when in ERD mode

### PR DESCRIPTION
**Pull request by djerius**
I'm using Dia 0.97 and discovered that a foreign key association equivalent to `t/data/long_fk_name.dia` was not accepted (a warning about incorrect multiplicity was issued and the foreign key sql was not generated).  I rewrote `t/data/long_fk_name.dia` using Dia 0.97 and it also was not accepted.

This commit does two things:

1. It adds a test which compares the sql generated from the existing test files with equivalent ones generated by Dia 0.97 to ensure that they are equivalent.
2. It fixes the above bug, which was due to the "aggregate" attribute not being added in ERD mode.

### CODE REVIEW

**Comment by djerius** [comment]
Ooops.  I misdiagnosed the problem and fix, even though all of the tests pass!   The "fix" breaks one-to-one associations.  Commit [4281ee1](https://github.com/aff/Parse-Dia-SQL/pull/7/commits/4281ee132a36b7c32a87125feed823dd25226bda) is still a valid one, as that provides the test showing the problem.

**Comment by aff** [comment]
Hi djerius
Thank you for your contribution. I do not currently have the capacity to review your work. I'll will get back to it late time permitting. Thank you.
BR
Andreas

**Comment by djerius** [comment]
​ ​
It would be useful to keep this issue open until you have time to review
it.  Others may run into the same problem and this solution may work for
them.  If the issue is closed they will most likely not see it.

**Comment by aff** [comment]
Closed by mistake.

**Comment by djerius** [comment]
> Closed by mistake.

 Thanks for reopening it.

**Pull request merged**
